src/album/albumview/leftlistview.cpp

原因是左侧栏标签中保存的对应的相册UID没有初始化，导致在内存中的状态是随机的，从而触发异常跳转
修复方法是加上初始化操作
Log: 修复相册界面异常跳转
Bug: https://pms.uniontech.com/bug-view-134081.html

fix: 修复相册界面异常跳转

---

src/CMakeLists.txt
src/album/widgets/printhelper.cpp

Description: 由于wayland和x11对于dialog的处理不同,需要指定父指针
Log: 与打印有关
Bug: https://pms.uniontech.com/bug-view-136519.html

fix: 修复bug136519

---

src/album/widgets/dialogs/videoinfodialog.cpp
src/album/widgets/dialogs/videoinfodialog.h

原因是在wayland环境下，在外部进行move和在showEvent里面move完成后的坐标是不一样的，相当于会先后move两次
解决方法是移除视频信息弹窗的showEvent代码
Log: 修复wayland环境下视频信息弹窗的位置是随机的
Bug: https://pms.uniontech.com/bug-view-135175.html

fix: 修复wayland环境下视频信息弹窗的位置是随机的

---

src/album/albumview/leftlistview.cpp

Description: 大小调整事件交由DScrollArea处理，保证滚动条正常显示
Log: 修复窗口尺寸由大调到最小时，自定义相册列表滚动条无法正常唤起的问题
Bug: https://pms.uniontech.com/bug-view-111262.html

fix: 修复窗口尺寸由大调到最小时，自定义相册列表滚动条无法正常唤起的问题

---

src/album/widgets/expansionpanel.cpp

Description: 去掉额外添加的圆角设置代码
Log: 解决非特效模式下，相册删选弹窗四角显示黑框的问题
Bug: https://pms.uniontech.com/bug-view-137209.html

fix: 解决非特效模式下，相册删选弹窗四角显示黑框的问题

---

src/album/albumview/leftlistview.cpp

原因是切换至已导入和最近删除的lab后，没有刷新当前UID的值
解决方法是添加刷新代码
Log: 修复相册界面左侧栏当前UID指向错误
Bug: https://pms.uniontech.com/bug-view-134081.html

fix: 修复相册界面左侧栏当前UID指向错误

---

src/album/imageengine/movieservice.cpp
src/album/imageengine/movieservice.h

原因是在多个线程中使用同一个QRegExp，通过检查Qt源代码发现，对同一个QRegExp实例来说，QRegExp::cap是不可重入的
解决方法是采用局部变量的QRegExp，不再使用类成员变量的形式
Log: 修复多线程读取视频信息时偶发崩溃
Bug: https://pms.uniontech.com/bug-view-142057.html

fix: 修复多线程读取视频信息时偶发崩溃

---

src/album/thumbnail/thumbnaillistview.cpp

Description: 解决搜索结果多选文件，不显示收藏菜单项的问题
Log: 解决搜索结果多选文件，不显示收藏菜单项的问题
Bug: https://pms.uniontech.com/bug-view-140767.html

fix: 解决搜索结果多选文件，不显示收藏菜单项的问题

---

src/album/albumview/albumview.cpp
src/album/widgets/batchoperatewidget.cpp

Description: 顶部操作栏不显示时，重新调整标题标签显示大小
Log: 解决最小尺寸，最近删除清空后，最近删除标题显示不完整的问题
Bug: https://pms.uniontech.com/bug-view-138659.html

fix: 解决最小尺寸，最近删除清空后，最近删除标题显示不完整的问题

---

src/album/imageengine/imageengineapi.cpp

Description: 双核心下，保证线程池最大数大于2
Log: 解决双核心或更低配置下，空相册导入图片卡死的问题

fix: 解决双核心或更低配置下，空相册导入图片卡死的问题

---

src/album/albumview/albumview.cpp

Description: 相册卸载回调不再强制重载外设
Log: 解决文管卸载外设后，相册依然刷新显示外设列表的问题
Bug: https://pms.uniontech.com/bug-view-141657.html

fix: 解决文管卸载外设后，相册依然刷新显示外设列表的问题

---

src/CMakeLists.txt

Log: check libimageviewer by pkgconfig
related: https://github.com/linuxdeepin/image-editor/pull/27

feat: use pkgconfig to find libimageviewer

---

src/album/widgets/dialogs/imginfodialog.cpp

Description: 标题栏文本框太短，字符长了显示不下。增加标题栏文本框长度，同时设置可自动换行。
Log: 修复系统语言为“波兰语”时，图片信息弹框上标题显示不全
Bug: https://pms.uniontech.com/bug-view-158545.html

fix: 修复系统语言为“波兰语”时，图片信息弹框上标题显示不全

---

src/album/dbmanager/dbmanager.cpp
src/album/utils/baseutils.cpp
src/album/utils/baseutils.h

Description: 添加删除回收站对应文件函数，在“最近删除”里面删除时调用
Log: 修复最近删除中的图片文件被永久删除后，回收站中未物理删除仍然存在该文件的问题
Bug: https://pms.uniontech.com/bug-view-157453.html

fix: 修复最近删除中的图片文件被永久删除后，回收站中未物理删除仍然存在该文件的问题

---

src/album/albumview/albumview.cpp
src/album/albumview/albumview.h
src/album/dbmanager/dbmanager.cpp
src/album/imageengine/imageengineapi.cpp
src/album/imageengine/imageengineapi.h
src/album/imageengine/imageenginethread.cpp
src/album/imageengine/imageenginethread.h
src/album/utils/baseutils.cpp
src/album/utils/baseutils.h

Description: 相册添加主动监视回收站机制，启动一个线程，每秒钟轮询一次所有最近删除的文件，如果在回收站中找不到，就删除
Log: 修复回收站删除、还原与相册的最近删除未同步问题
Bug: https://pms.uniontech.com/bug-view-158861.html

fix: 修复回收站删除、还原与相册的最近删除未同步问题

---

src/album/imageengine/imageengineapi.cpp
src/album/imageengine/imageengineapi.h
src/album/mainwindow.cpp
tests/dialogs/test_dialogs.cpp
tests/test_mainwindow.cpp

Description: 程序退出时停止“同步回收站与最近删除”线程
Log: 修复2022/10/24 单元测试出现异常
Bug: https://pms.uniontech.com/bug-view-166419.html

fix: 修复2022/10/24 单元测试出现异常

---

src/album/controller/configsetter.cpp

原因是多线程执行配置文件读写，导致QSetting内部负责group管理的QStack崩溃
解决方法是加上线程锁
Log: 修复删除配置文件后重启相册，有概率导致相册崩溃
Bug: https://pms.uniontech.com/bug-view-169613.html

fix: 修复删除配置文件后重启相册，有概率导致相册崩溃

---

src/album/dialogs/albumcreatedialog.cpp
src/album/widgets/albumlefttabitem.cpp

根据需求文档要求，将相册名的创建长度和重命名均限制在255个字符以内
Log: 修复未限制相册名长度
Bug: https://pms.uniontech.com/bug-view-164741.html

fix: 修复未限制相册名长度

---

src/album/dbmanager/dbmanager.cpp
src/album/dialogs/albumcreatedialog.cpp
src/album/utils/baseutils.h
src/album/widgets/albumlefttabitem.cpp

现象是当相册名存在特殊SQL字符时，会导致相册创建失败
解决方法是使用SQLite3自带的转义工具进行转义，确保带特殊字符的相册创建成功
Log: 修复部分数据库读写操作未对字符串进行转义
Bug: https://pms.uniontech.com/bug-view-163535.html

fix: 修复部分数据库读写操作未对字符串进行转义

---

src/album/albumview/leftlistview.cpp

Description: 相册目录切换时，选中项改变事件中，刷新右侧详情
Log: 修复通过键盘上下键切换相册目录时，右侧详情未同步刷新
Bug: https://pms.uniontech.com/bug-view-165483.html

fix: 修复通过键盘上下键切换相册目录时，右侧详情未同步刷新

---

src/album/searchview/searchview.cpp

Description: 播放幻灯片，传入当前窗口id
Log: 修复在相册sheet页面，搜索后幻灯片播放并结束，自动调整到所有照片sheet
Bug: https://pms.uniontech.com/bug-view-164731.html

fix: 修复在相册sheet页面，搜索后幻灯片播放并结束，自动调整到所有照片sheet

---

src/album/albumview/albumview.cpp

Description: 导入完成后不跳转窗口
Log: 修复当存在两个外设时，在第二个外设导入成功后，自动切换到第一个外设
Bug: https://pms.uniontech.com/bug-view-164385.html

fix: 修复当存在两个外设时，在第二个外设导入成功后，自动切换到第一个外设

---

src/album/widgets/albumlefttabitem.cpp

Description: 标签不显示多文本内容
Log: 修复新建相册时，输入html标签，会被解析成页面的问题
Bug: https://pms.uniontech.com/bug-view-163847.html

fix: 修复新建相册时，输入html标签，会被解析成页面的问题

---

src/album/widgets/albumlefttabitem.cpp

Description: 调整控件宽度，调整控件文本初始化，调整控件宽度设置与文本初始化顺序
Log: 修复外设为6个中文汉字时，名称显示不完整
Bug: https://pms.uniontech.com/bug-view-164729.html

fix: 修复外设为6个中文汉字时，名称显示不完整

---

src/album/albumview/albumview.cpp

Description: 挂载设备数据更新完成后设置右视图获取焦点
Log: 修复相册界面插入U盘,相册顶栏+展示Focus状态
Bug: https://pms.uniontech.com/bug-view-164389.html

fix: 修复相册界面插入U盘,相册顶栏+展示Focus状态

---

src/album/albumview/albumview.cpp

Description: 挂载标签的显隐不应由mount数决定，改为由设备列表是否内容来决定，设备列表无内容，隐藏设备标签，否则显示
Log: 修复移除挂载收集设备时，设备模块偶现未被移除的问题
Bug: https://pms.uniontech.com/bug-view-164351.html

fix: 修复移除挂载手机设备时，设备模块偶现未被移除的问题

---

src/album/albumview/albumview.cpp
src/album/albumview/albumview.h
src/album/widgets/batchoperatewidget.cpp
src/album/widgets/batchoperatewidget.h
src/album/widgets/expansionmenu.cpp
src/album/widgets/expansionmenu.h

Description: 筛选按钮宽度发生变化后，发出消息，通知标题栏做出相应调整
Log: 修复相册名称过长时与界面控件重叠
Bug: https://pms.uniontech.com/bug-view-164275.html

fix: 修复相册名称过长时与界面控件重叠

---

src/album/mainwindow.cpp

Description: 切换gif图片，sigOneImgReady没有发送到外部，导致外部没有设置windowtitle。更换信号为 sigUpdateCollectBtn
Log: 看图切换图片后，xwininfo读取路径有时没有变化
Bug: https://pms.uniontech.com/bug-view-177025.html

fix: 看图切换图片后，xwininfo读取路径有时没有变化

---

src/qml/SideBar/SideBarItemDelegate.qml

重设侧边栏的调色板，保证侧边栏条目checked状态下图标颜色显示正常
Log: 修复侧边栏选中图标颜色未取反的问题

fix: 修复侧边栏选中图标颜色未取反的问题

---

src/qml/PreviewImageViewer/OpenImageWidget.qml
src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml

修复文管选择多张图片，右键相册打开不能导入相册的问题
Log: 修复文管选择多张图片，右键相册打开不能导入相册的问题
Bug: https://pms.uniontech.com/bug-view-185441.html

fix: 修复文管选择多张图片，右键相册打开不能导入相册的问题

---

src/src/filecontrol.cpp

应使用url路径判断是否为图片
Log: 修复双击打开图片提示不支持格式的问题

fix: 修复双击打开图片提示不支持格式的问题

---

src/album/albumview/albumview.cpp
src/album/albumview/albumview.h
src/album/dbmanager/DBandImgOperate.cpp

该架构下，存在插入U盘连续发送三组挂载/卸载设备信号的情况，该过程极易导致相册QDirIterator遍历无效目录（已卸载设备目录自然是无效路径）而crash，因此针对loongarch架构机器，做出优化，在收到最后一次挂载信号500ms后，才开始扫描挂载设备目录
Log: 修复loongarch架构插入U盘闪退的问题
Bug: https://pms.uniontech.com/bug-view-190769.html

fix: 修复loongarch架构插入U盘闪退的问题

---

src/qml/AlbumTitle.qml

调整右侧图片操作按钮布局大小为固定尺寸，保证搜索框位置不再乱跳
Log: 【UI】修复选中照片时，搜索输入框会跳动的问题
Bug: https://pms.uniontech.com/bug-view-183481.html

fix: 【UI】修复选中照片时，搜索输入框会跳动的问题

---

src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml
src/src/thumbnailview/thumbnailmodel.cpp

原因是最近删除视图缓存图片加载成功后，缩略图model类图片路径校验出错，解决方案是针对最近删除的图片刷新逻辑添加路径判断
Log: 修复删除图片后，最近删除视图部分图片显示为撕裂图的问题
Bug: https://pms.uniontech.com/bug-view-170385.html

fix: 修复删除图片后，最近删除视图部分图片显示为撕裂图的问题

---

src/qml/AlbumTitle.qml
src/qml/MainAlbumView.qml

原因是标题栏布局实现调整，导致标题栏内无法访问到新建相册对话框对象，解决方案是发送信号到主界面，通知显示新建相册对话框
Log: 修复右上角菜单-新建相册无反应的问题
Bug: https://pms.uniontech.com/bug-view-192979.html

fix: 修复右上角菜单-新建相册无反应的问题

---

.reuse/dep5
3rdparty/tiff-tools/converttiff.h
3rdparty/tiff-tools/tiffcp.c
LICENSES/libtiff.txt
README.md
README.zh_CN.md
debian/control
debian/copyright
libUnionImage/UnionImage/unionimage.cpp
libUnionImage/UnionImage/unionimage.h
src/CMakeLists.txt

对使用ojpeg压缩格式或读取异常的图片，尝试转换文件压缩格式，从转换后的文件读取tif图片数据，并移除转换后的文件
Log: 修复相册不能显示tiff图片的问题
Bug: https://pms.uniontech.com/bug-view-191409.html

fix: 修复相册不能显示tiff图片的问题

---

src/album/dbmanager/DBandImgOperate.cpp
src/album/dbmanager/DBandImgOperate.h
src/album/imageengine/imageengineapi.cpp
src/album/imageengine/imageengineapi.h
src/album/mainwindow.cpp

U盘格式化时，调用sync命令同样会被阻塞，调整sync命令调用时机，仅在旋转和读图时才执行sync命令阻塞相册关闭
Log: 修复U盘格式化过程中，无法关闭相册应用的问题
Bug: https://pms.uniontech.com/bug-view-164375.html

fix: 修复U盘格式化过程中，无法关闭相册应用的问题

---

src/album/albumview/albumview.cpp
src/album/widgets/batchoperatewidget.cpp

1.调整自定义相册顶部控件显示布局和计算方式
2.调整我的收藏顶部控件显示布局和计算方式
Log: 修复相册名称为单字符时，相册名会与顶部控件区域重叠的问题
Bug: https://pms.uniontech.com/bug-view-138675.html

fix: 修复相册名称为单字符时，相册名会与顶部控件区域重叠的问题

---

src/album/widgets/albumlefttabitem.cpp
src/album/widgets/albumlefttabitem.h

1.添加paintEvent事件处理，在窗口未激活时，设置图标为置灰状态
2.调整文本颜色UI效果
Log: 修复相册窗口处于未激活状态下，相册导航栏图标未置灰的问题
Bug: https://pms.uniontech.com/bug-view-156983.html

fix: 修复相册窗口处于未激活状态下，相册导航栏图标未置灰的问题

---

src/album/widgets/dialogs/imginfodialog.cpp

调整抽屉界面整体高度，以便下边距与左右边距一致
Log: 修复图片信息-仅展示基本信息时下边距过宽的问题
Bug: https://pms.uniontech.com/bug-view-156997.html

fix: 修复图片信息-仅展示基本信息时下边距过宽的问题

---

src/album/mainwindow.cpp
src/album/mainwindow.h

添加删除确认信号的处理，来自看图的删除信号，弹出删除确认弹窗
Log: 修复大图模式删除图片，没有显示删除确认弹窗的问题
Bug: https://pms.uniontech.com/bug-view-157033.html

fix: 修复大图模式删除图片，没有删除确认弹窗的问题

---

src/album/widgets/albumlefttabitem.cpp

补齐tooltips文案显示逻辑
Log: 修复相册视图-导航栏，相册名称没有tooltips提示文案的问题
Bug: https://pms.uniontech.com/bug-view-194271.html

fix: 修复相册视图-导航栏，相册名称没有tooltips提示文案的问题

---

src/album/albumview/leftlistview.cpp
src/album/albumview/leftlistview.h

应用的鼠标移动事件需要被接受，平台插件(dde-qt5platform-plugins)才不会移动窗口
Log: 修复相册视图-侧边栏空白区域，可移动相册主界面的问题
Bug: https://pms.uniontech.com/bug-view-194203.html

fix: 修复相册视图-侧边栏空白区域，可移动相册主界面的问题

---

src/album/albumview/leftlistview.cpp
src/album/albumview/leftlistwidget.cpp
src/album/albumview/leftlistwidget.h
src/album/mainwindow.cpp
src/album/mainwindow.h
src/album/widgets/flatbutton.cpp
src/album/widgets/flatbutton.h

1.添加FlatButton，支持Flat类型按钮可显示hover样式
2.列表控件代理背景类型不能被设置为NoBackground类型，否则会丢失hover样式，修改为重写ListWidget的paint事件，在paint事件中定义子项背景色，以保证颜色与主题背景色一致
Log: 修复侧边栏导航项和标题栏按钮缺少hover样式的问题
Bug: https://pms.uniontech.com/bug-view-194199.html

fix: 修复侧边栏导航项和标题栏按钮缺少hover样式的问题

---

src/album/mainwindow.cpp

根据UI设计规范，“+”按钮应与系统按钮组间隔10px，因此添加一个10px宽空白部件隔开
Log: 【UI】标题栏布局调整，“+”按钮与系统按钮组间隔10px
Bug: https://pms.uniontech.com/bug-view-194217.html

chore: 【UI】标题栏布局调整，“+”按钮与系统按钮组间隔10px

---

src/album/albumview/albumview.cpp

窗口大小调整时，根据显示内容重置设备总数标签默认宽度值
Log: 修复设备总数标签内容显示不全的问题
Bug: https://pms.uniontech.com/bug-view-194225.html

fix: 修复设备总数标签内容显示不全的问题

---

src/album/albumview/leftlistview.cpp

【UI】侧边栏显示顺序调整，从上到下依次为照片库->相册->设备
Log: 【UI】侧边栏显示顺序调整，从上到下依次为照片库->相册->设备
Bug: https://pms.uniontech.com/bug-view-194229.html

chore: 【UI】侧边栏显示顺序调整，从上到下依次为照片库->相册->设备

---

src/album/thumbnail/thumbnaildelegate.cpp

使用dtk风格绘制选中图标，以便选中图标背景色跟随主题高亮颜色改变
Log: 【UI】选中图标颜色跟随主题高亮颜色改变
Bug: https://pms.uniontech.com/bug-view-194241.html

chore: 【UI】选中图标颜色跟随主题高亮颜色改变

---

src/album/widgets/albumlefttabitem.cpp

【UI】侧边栏-导航项名称，仅在显示不全时，才显示悬浮提示
Log: 【UI】侧边栏-导航项名称，仅在显示不全时，才显示悬浮提示
Bug: https://pms.uniontech.com/bug-view-194271.html

fix: 【UI】侧边栏-导航项名称，仅在显示不全时，才显示悬浮提示

---

src/album/widgets/flatbutton.cpp

【UI】相册标题栏扁平按钮悬浮色调整，保持与侧边栏悬浮色一致
Log: 【UI】相册标题栏扁平按钮悬浮色调整，保持与侧边栏悬浮色一致
Bug: https://pms.uniontech.com/bug-view-194199.html

chore: 【UI】相册标题栏扁平按钮悬浮色调整，保持与侧边栏悬浮色一致

---

src/album/mainwindow.cpp
src/album/mainwindow.h

相册-大图删除按钮逻辑整理：
a.老版本，直接删除图片，保持和看图逻辑一致
b.新版本，弹出删除确认弹窗
image-editor相关pr:
https://github.com/linuxdeepin/image-editor/pull/77
Log: 修复低版本相册点击大图-删除按钮无效的问题

fix: 修复低版本相册点击大图-删除按钮无效的问题

---

debian/control

因image-editor添加删除确认提示功能，相册需强依赖image-editor 1.0.29以上版本
Log: 相册强依赖image-editor1.0.29以上版本
Bug: https://pms.uniontech.com/bug-view-197551.html

chore: 相册强依赖image-editor 1.0.29以上版本

---

src/qml/AlbumTitle.qml

It is a bug for `dtkdeclarative`, but we can avoid it.
Issue: https://github.com/linuxdeepin/developer-center/issues/4222

fix: AboutDialog's titlebar tearing shadow

---

src/album/mainwindow.cpp

适配紧凑模式，使用setVisible()替换setFixedHeight(),
避免DTK更新标题栏高度时出现多个标题栏。
Log: Adapt to compact mode.
Influence: CompactMode

fix: Adapt to compact mode.

---

debian/changelog

Update version to 5.10.19
适配紧凑模式，相关PR：
* https://github.com/linuxdeepin/deepin-album/pull/164
* https://github.com/linuxdeepin/deepin-album/pull/165
* https://github.com/linuxdeepin/deepin-album/pull/166
Log: Update version to 5.10.19

chore: Update version to 5.10.19

---

src/main.cpp

相册应用使用Qt::AA_UseHighDpiPixmaps属性
Log: 修复高分屏图标显示过大的问题
Issue: https://github.com/linuxdeepin/developer-center/issues/4884

fix: 修复高分屏图标显示过大的问题

---

src/src/albumControl.cpp
src/src/albumControl.h

将扫描设备路径流程放置到点击设备时执行，节省相册启动时间
Log: 相册挂载外设时，启动时间优化
Bug: https://pms.uniontech.com/bug-view-185733.html

fix: 相册挂载外设时，启动时间优化

---

src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/src/imageengine/imagedataservice.cpp
src/src/thumbnailload.cpp
src/src/thumbnailload.h

限制年/月视图Image控件请求的图片最大不超过1000*618，以避免年/视图图片因缓存原始尺寸图片而占用过大内存
Log: 内存优化

perf: 内存优化

---

src/main.cpp
src/qml/AlbumTitle.qml
src/qml/Control/ListView/ThumbnailListView2.qml
src/qml/MainAlbumView.qml
src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
src/qml/ThumbnailImageView/CustomAlbum/CustomAlbum.qml
src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml
src/qml/main.qml
src/src/globalstatus.h
src/src/imageengine/imagedataservice.cpp
src/src/thumbnailload.cpp
src/src/thumbnailview/imagedatamodel.cpp

1.未显示的视图，不加载其内容
2.解决重启后，缩略图大小显示不对的问题
3.解决界面宽度调整后，略图列表右侧有较大留白区域的问题
4.使用Dtk日志接口输出日志信息
5.修复相册启动时，侧边栏图标严重闪烁的问题(启动时不加载年/月视图)
6.调整缩略图缓存尺寸为180*180
Log: 相册启动时间优化，并解决部分bug

perf: 相册启动时间优化，并解决部分bug

---

src/main.cpp
src/qml/Control/ListView/ThumbnailListDelegate.qml
src/qml/Control/ListView/ThumbnailListDelegate2.qml
src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
src/src/thumbnailview/qimageitem.cpp
src/src/thumbnailview/qimageitem.h

1.使用Component动态加载选中框、剩余天数、视频时长等控件
2.QImageItem为空时，默认显示撕裂图，节省C++/model类型的缩略图列表创建撕裂图的时间开销（约500ms）
3.Dci图标撕裂图显示异常问题解决，并实现在C++中加载撕裂图
Log: 优化缩略图列表代理控件加载速度

perf: 优化缩略图列表代理控件加载速度

---

src/src/albumControl.cpp

对于smb路径，DGioMount::getVolume()接口需要判空，否则程序崩溃
Log: 修复存在smb路径时，相册闪退的问题
Bug: https://pms.uniontech.com/bug-view-217933.html

fix: 修复存在smb路径时，相册闪退的问题

---

src/src/albumControl.cpp
src/src/albumControl.h
src/src/imageengine/imageenginethread.cpp
src/src/imageengine/imageenginethread.h

1.优化单例类AlbumControl构建流程，其构造函数的调用链中不能迭代调用AlbumControl::instance()
2.优化链接图片处理流程
Log: 修复导入链接图片后，相册二次启动失败的问题
Bug: https://pms.uniontech.com/bug-view-218077.html

fix: 修复导入链接图片后，相册二次启动失败的问题

---

src/qml/Control/ListView/ThumbnailListDelegate.qml

Imported view eliminates thumbnail excess projection boundaries
Log: Imported view eliminates thumbnail excess projection boundaries

fix: Imported view eliminates thumbnail excess projection boundaries

---

src/album/mainwindow.cpp

Fix the issue of empty interface after exiting the slide show
Log: Fix the issue of empty interface after exiting the slide show
Bug: https://pms.uniontech.com/bug-view-205055.html

fix: Fix the issue of empty interface after exiting the slide show

---

src/album/thumbnail/thumbnaillistview.cpp

Disabled right-click menu for photo classification cover page
Log: Disabled right-click menu for photo classification cover page
Bug: https://pms.uniontech.com/bug-view-232551.html

fix: Disabled right-click menu for photo classification cover page

---

src/album/albumview/albumview.cpp
src/album/mainwindow.cpp

Hide search box on photo classification cover page
Log: Hide search box on photo classification cover page
Bug: https://pms.uniontech.com/bug-view-232637.html

fix: Hide search box on photo classification cover page

---

src/album/albumview/albumview.cpp

Resolve the issue of invalid delete key on photo classification detail page
Log: Resolve the issue of invalid delete key on photo classification detail page
Bug: https://pms.uniontech.com/bug-view-232631.html

fix: Resolve the issue of invalid delete key on photo classification detail page

---

src/album/mainwindow.cpp

Resolve the issue of entering slide mode after viewing images and exiting without a title bar
Log: Resolve the issue of entering slide mode after viewing images and exiting without a title bar
Bug: https://pms.uniontech.com/bug-view-232641.html

fix: Resolve the issue of entering slide mode after viewing images and exiting without a title bar

---

src/album/mainwindow.cpp
src/album/mainwindow.h

Resolve the issue of being able to close alt+F4 when importing progress bars
Log: Resolve the issue of being able to close alt+F4 when importing progress bars
Bug: https://pms.uniontech.com/bug-view-232643.html

fix: Resolve the issue of being able to close alt+F4 when importing progress bars

---

src/album/controller/wallpapersetter.cpp

设置锁屏背景的图片过大,后端DBus可能返回文件过大错误,
调整压缩格式PNG为JPG,同时过大的PNG/JPG图片也会被压缩.
Log: 修复设置大图片为壁纸无反应的问题
Bug: https://pms.uniontech.com/bug-view-247311.html
Influence: SetWallpaper

fix: Cached greeter background image too large

---

src/album/controller/wallpapersetter.cpp
src/album/thumbnail/thumbnaillistview.cpp
src/album/utils/baseutils.cpp
src/album/utils/baseutils.h

缓存图片后缀和格式保持相同, 提高压缩率
部分图片格式不支持，新增格式判断函数和看图一致
Log: 过滤不支持设置为壁纸的图片格式
Bug: https://pms.uniontech.com/bug-view-247311.html
Influence: SetWallpaper

fix: Filter image format not support wallpaper 

---

debian/changelog

Bump version to 5.10.23
PR:
* https://github.com/linuxdeepin/deepin-album/pull/205
* https://github.com/linuxdeepin/deepin-album/pull/206
* https://github.com/linuxdeepin/deepin-album/pull/207
Bump version to 5.10.23

chore: Bump version to 5.10.23

---

src/qml/Control/DeleteDialog.qml
src/qml/Control/NewAlbumDialog.qml
src/qml/Control/RemoveAlbumDialog.qml

Modify pop-up window style, include delete photo and create album
Log: [UI] Modify pop-up window style
Bug: https://pms.uniontech.com/bug-view-193023.html, https://pms.uniontech.com/bug-view-168193.html

fix: [UI] Modify pop-up window style

---

src/qml/Control/ListView/ThumbnailListDelegate.qml
src/qml/Control/ListView/ThumbnailListDelegate2.qml

Optimize the selected icon position
Log: Optimize the selected icon position

fix: Optimize the selected icon position

---

src/qml/Control/ExportDialog.qml
src/translations/deepin-album.ts
src/translations/deepin-album_zh_CN.ts

[UI] Modify Export pop-up window style
Log: [UI] Modify Export pop-up window style
Bug: https://pms.uniontech.com/bug-view-168215.html

fix: [UI] Modify Export pop-up window style

---

src/qml/AlbumTitle.qml

Adjust the logic of the search box clear button function
1.when user clicked clear button, back to previous view.
Log: Adjust the logic of the search box clear button function
Bug: https://pms.uniontech.com/bug-view-168261.html

fix: Adjust the logic of the search box clear button function

---

src/qml/AlbumTitle.qml

Hide image operation button group on recently delete view
Log: Hide image operation button group on recently delete view
Bug: https://pms.uniontech.com/bug-view-192935.html

fix: Hide image operation button group on recently delete view

---

src/qml/GlobalVar.qml
src/qml/MainAlbumView.qml

Resolve the issue of floating prompts popping up multiple times due to import failure
Log: Resolve the issue of floating prompts popping up multiple times due to import failure
Bug: https://pms.uniontech.com/bug-view-192991.html

fix: Resolve the issue of floating prompts popping up multiple times due to import failure

---

src/qml/AlbumTitle.qml
src/qml/Control/ListView/ThumbnailListViewTools.js
src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml

1.Resolve the issue of not hiding image operation buttons after deleting all images
2.fix titlebar left area has shadow‘s problem
Log: Resolve the issue of not hiding image operation buttons after deleting all images
Bug: https://pms.uniontech.com/bug-view-168547.html

fix: Resolve the issue of not hiding image operation buttons after deleting all images

---

src/deepin-album.qrc
src/qml/AlbumTitle.qml
src/qml/Control/Animation/SwitchViewAnimation.qml
src/qml/Control/DeleteDialog.qml
src/qml/Control/ListView/ThumbnailListDelegate.qml
src/qml/Control/ListView/ThumbnailListDelegate2.qml
src/qml/Control/ListView/ThumbnailListView.qml
src/qml/Control/ListView/ThumbnailListView2.qml
src/qml/SideBar/SideBarItem.qml
src/qml/SideBar/SideBarItemDelegate.qml
src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
src/src/globalstatus.cpp
src/src/globalstatus.h

Add collection animation effects
Log: [UI] Add collection animation effects

feat: [UI] Add collection animation effects

---

src/qml/AlbumTitle.qml
src/qml/Control/Animation/SwitchViewAnimation.qml
src/qml/StatusBar.qml
src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
src/qml/ThumbnailImageView/ThumbnailImage.qml
src/src/globalstatus.cpp
src/src/globalstatus.h
src/src/types.h

Add switch types to set animation switching effects
Log: Add switch types to set animation switching effects

feat: Add switch types to set animation switching effects

---

src/main.cpp
src/qml/Control/Animation/SwitchViewAnimation.qml
src/qml/Control/BorderImageEx.qml
src/qml/Control/MonthImage.qml
src/qml/PreviewImageViewer/ImageViewer.qml
src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
src/qml/ThumbnailImageView/ThumbnailImage.qml
src/src/albumControl.cpp
src/src/albumControl.h
src/src/configsetter.cpp
src/src/globalstatus.cpp
src/src/globalstatus.h

1.Resolve the issue where clicking on the annual cover image cannot accurately locate the monthly view
2.Fixed the issue of occasional blank content views when clicking on the monthly view
3.Add fade in animation effect to the large image preview component
4.Add config for animation duration
Log: Collection of knwon problem fixes

fix: Collection of known problem fixes

---

src/main.cpp
src/qml/AlbumTitle.qml
src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
src/qml/main.qml

Add a semi transparent background effect to the sidebar
Log: [UI] Add a semi transparent background effect to the sidebar
Bug: https://pms.uniontech.com/bug-view-265267.html

fix: [UI] Add a semi transparent background effect to the sidebar

---

src/qml/PreviewImageViewer/ToolBarThumbnailListView.qml
src/qml/SideBar/SideBarItemDelegate.qml
src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml

1.Add hover status display to the sidebar sub item
2.Large image preview shows rotation button
3.Adjust the bottom margin of the year/month view to 25px, top marigin to 0px
Log: [UI] Add hover status display to the sidebar sub item
Bug: https://pms.uniontech.com/bug-view-268929.html, https://pms.uniontech.com/bug-view-268925.html

fix: [UI] Add hover status display to the sidebar sub item

---

src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml

The first sub item has a top margin of 12.5px, the last sub item has a bottom margin of 12.5px, and the middle sub item has a spacing of 25px
Log: [UI] Adjustment of Top and Bottom Margins in Year Month View
Bug: https://pms.uniontech.com/bug-view-268925.html

fix: [UI] Adjustment of Top and Bottom Margins in Year Month View

---

src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml

Resolve the issue of overlapping display of recently deleted tag content and recovery button
Log: Resolve the issue of overlapping display of recently deleted tag content and recovery button
Bug: https://pms.uniontech.com/bug-view-269761.html

fix: Resolve the issue of overlapping display of recently deleted tagcontent and recovery button

---

src/main.cpp
src/qml/SideBar/Sidebar.qml
src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml

Resolve the issue of the probability of crashing when switching to an imported view
Log: Resolve the issue of the probability of crashing when switching to an imported view
Bug: https://pms.uniontech.com/bug-view-271803.html

Resolve the issue of the probability of crashing when switching to an imported view

---

src/qml/main.qml
src/src/globalcontrol.cpp
src/src/globalcontrol.h

Fixed the issue of waiting for restart after exiting
Bug: https://pms.uniontech.com/bug-view-289903.html
Log: Fixed the issue of waiting for restart after exiting

fix: Fixed the issue of waiting for restart after exiting

---

src/qml/Control/ListView/ThumbnailListViewTools.js
src/src/albumControl.cpp
src/src/thumbnailview/imagedatamodel.cpp
src/src/thumbnailview/roles.h
src/src/thumbnailview/thumbnailmodel.cpp
src/src/thumbnailview/thumbnailmodel.h

[fix: check deepin-movie installed in linglong](https://github.com/linuxdeepin/deepin-album/commit/92f72a2eaf5fdc468296e34f502cb393c2f9d99a) 
As title, we need check deepin-movie installed in
linglong before execute it.
Log: check deepin-movie installed before execute.
[fix: image viewer contain videos](https://github.com/linuxdeepin/deepin-album/commit/4c2b5fc4d5caf75bb5e6ade4e12d0cabf2eb1ef0) 
Image viewer not need show videos.
Log: image viewer remove videos.
Bug: https://pms.uniontech.com/bug-view-295427.html

fix: image viewer contain videos

---

README.md
README.zh_CN.md

remove invalid  url
Log: remove invalid  url

fix: remove invalid  url

---

src/src/dbmanager/dbmanager.cpp

The Udisk mount path changed start with "/run/media/..", add "/mnt/" for user mount case.
Log: Fix be able to insert Udisk pictures into trash issue.
Bug: https://pms.uniontech.com/bug-view-289199.html

fix: Fix be able to insert Udisk pictures into trash issue

---

src/qml/MainAlbumView.qml
src/qml/MenuItemStates.qml
src/src/albumControl.cpp
src/src/albumControl.h
src/src/dbmanager/dbmanager.cpp
src/src/dbmanager/dbmanager.h

Update the file path in database and notify refresh after rename; flush all collection view if delete from it.
Log: Update image info after rename.
Bug: https://pms.uniontech.com/bug-view-308075.html
https://pms.uniontech.com/bug-view-300873.html

fix: Update image info after rename
