linuxdeepin/deepin-album

- src/album/albumview/albumview.cpp
- src/album/albumview/albumview.h
- src/album/importtimelineview/importtimelineview.cpp
- src/album/mainwindow.cpp
- src/album/mainwindow.h
Description: 完善相关逻辑
Log: 解决控制中心切换字体大小20后，相册所有页面显示异常的问题
Bug: https://pms.uniontech.com/bug-view-131369.html
> fix: 解决控制中心切换字体大小20后，相册所有页面显示异常的问题

- src/album/albumview/albumview.cpp
- src/album/imageengine/movieservice.cpp
- src/album/importtimelineview/importtimelineview.cpp
- src/album/mainwindow.cpp
Description: fontChanged信号在低版本不存在
Log: 最小尺寸兼容性问题修改
> fix: 最小尺寸兼容性问题修改

- src/album/thumbnail/thumbnaillistview.cpp
Description: 解决搜索结果右键收藏闪退的问题
Log: 解决搜索结果右键收藏闪退的问题
Bug: https://pms.uniontech.com/bug-view-140313.html
> fix: 解决搜索结果右键收藏闪退的问题

- tests/albumview/test_importtimelineview.cpp
Description: 修改一处Cppcheck检测的列表取值可能越界错误
Log: 修改一处Cppcheck检测的列表取值可能越界错误
Influence: 调试信息
> fix: 修改一处Cppcheck检测的列表取值可能越界错误

- src/album/application.cpp
- src/album/dbmanager/DBandImgOperate.cpp
- src/album/imageengine/imagedataservice.cpp
- src/album/utils/baseutils.cpp
- src/album/utils/baseutils.h
fix: 修复cppcheck错误
修复cppcheck错误
Log: 修复cppcheck错误
> Topic depend1091

- src/album/main.cpp
- src/album/utils/eventlogutils.cpp
- src/album/utils/eventlogutils.h
Description: 提交埋点需求，采集相册启动数据
Log: 提交埋点需求，采集相册启动数据
> feat: 提交埋点需求，采集相册启动数据

- debian/control
Description: 调整相册埋点依赖
Log: 调整相册埋点依赖
> feat: 调整相册埋点依赖

- .reuse/dep5
- debian/copyright
Description: 完善reuse和debian copyright的相关声明
Log: 完善reuse和debian copyright的相关声明
Influence: 无
> chore: 完善reuse和debian copyright的相关声明

- .reuse/dep5
- LICENSE.txt
- debian/copyright
Description: 修改License描述及部分文件的版权信息
Log: 修改License描述及部分文件的版权信息
Influence: 无
> chore: 修改License描述及部分文件的版权信息

- src/album/albumview/leftlistview.cpp
- src/album/albumview/leftlistwidget.cpp
- src/album/albumview/leftlistwidget.h
- src/album/widgets/albumlefttabitem.cpp
- src/album/widgets/albumlefttabitem.h
Description: 屏蔽侧边栏双击后可上下健切换功能
Log: 屏蔽侧边栏双击后可上下健切换功能
Bug: https://pms.uniontech.com/bug-view-165483.html
> fix: 屏蔽侧边栏双击后可上下健切换功能

- src/album/albumview/albumview.cpp
- src/album/thumbnail/thumbnaildelegate.cpp
Description: 在所有模式下，只要是已收藏的图片，缩略图左下角都绘制已收藏图标
Log: 修复【专业版】收藏交互问题
Bug: https://pms.uniontech.com/bug-view-157041.html
> fix: 修复【专业版】收藏交互问题

- debian/control
解决部分不升级image-editor就会存在的严重问题
Log: 解决部分不升级image-editor就会存在的严重问题
> fix: 修改image-editor依赖版本

- src/album/dbmanager/dbmanager.cpp
Description: 查询数据库表，查询出文件类型字段并赋值
Log: 修复相册内搜索视频文件结果呈图片
Bug: https://pms.uniontech.com/bug-view-161807.html
> fix: 修复相册内搜索视频文件结果呈图片

- src/qml/GlobalVar.qml
- src/qml/PreviewImageViewer/OpenImageWidget.qml
- src/qml/main.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
gerrit-V23代码合入
Log: gerrit-V23代码合入
> chore: gerrit-V23代码合入

- src/qml/SideBar/SideBarItem.qml
- src/qml/SideBar/SideBarItemDelegate.qml
- src/qml/SideBar/Sidebar.qml
侧边栏深色模式显示效果优化
Log: 侧边栏深色模式显示效果优化
Change-Id: I413c14f0789b96003c7391072474d5ea33147dd8
> fix: 侧边栏深色模式显示效果优化

- src/src/filecontrol.cpp
Description: 调整部分修改的DBus接口使用方式，以同时处理V20和V23的接口调用
Log: 适配V23 DDE DBus接口
Influence: DBus接口
> feat: 适配V23 DDE DBus接口

- src/src/filecontrol.cpp
Description: 添加详细的DBus调用日志信息
Log: 添加DBus调用日志
> style: 添加DBus调用日志

- .tx/deepin.conf
- debian/changelog
Update version to 5.10.11
Log: Update version to 5.10.11
> chore: Update verison to 5.10.11

- src/qml/AlbumTitle.qml
- src/qml/MainAlbumView.qml
标题栏布局方式有调整，需要更改标题栏删除按钮的响应方式
Log: 修复标题栏点删除无响应的问题
> fix: 修复标题栏点删除无响应的问题

- debian/changelog
update version to 5.10.12
Log: update version to 5.10.12
> chore: update version to 5.10.12

- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
- src/src/configsetter.cpp
- src/src/configsetter.h
- src/src/filecontrol.cpp
- src/src/filecontrol.h
通过配置文件控制日视图和已导入视图是否加载（用于调试）
Log: 通过配置文件控制日视图和已导入视图是否加载（用于调试）
> chore: 通过配置文件控制日视图和已导入视图是否加载（用于调试）

- src/qml/Control/ListView/ThumbnailListViewTools.js
- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
修复双击看图界面，不能全屏显示的问题
Log: 修复双击看图界面，不能全屏显示的问题
Bug: https://pms.uniontech.com/bug-view-185513.html
> fix: 修复双击看图界面，不能全屏显示的问题

- src/qml/Control/ListView/ThumbnailListView.qml
- src/qml/Control/ListView/ThumbnailListView2.qml
修复逆时针旋转菜单项下方多出分割线的问题
Log: 修复逆时针旋转菜单项下方多出分割线的问题
Bug: https://pms.uniontech.com/bug-view-168229.html
> fix: 修复逆时针旋转菜单项下方多出分割线的问题

- src/main.cpp
fix compile prolbem
Log: fix compile prolbem
> chore: fix compile prolbem

- src/qml/AlbumTitle.qml
- src/qml/Control/ListView/ThumbnailListView2.qml
- src/qml/GlobalVar.qml
- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
- src/qml/main.qml
默认第一次打开相册，移除切换到所有视图的动画效果
Log: 默认第一次打开相册，移除切换到所有视图的动画效果
Bug: https://pms.uniontech.com/bug-view-168169.html
> fix: 默认第一次打开相册，移除切换到所有视图的动画效果

- src/qml/GlobalVar.qml
- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
修复年/月视图与标题栏间距过小的问题
Log: 修复年/月视图与标题栏间距过小的问题
Bug: https://pms.uniontech.com/bug-view-183487.html
> fix: 修复年/月视图与标题栏间距过小的问题

- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
- src/src/thumbnailload.cpp
修复图片不显示圆角的问题，增加阴影效果，增加分割线
Log: 修复年月视图图片不显示圆角的问题
Bug: https://pms.uniontech.com/bug-view-170391.html
> fix: 修复年月视图图片不显示圆角的问题

- src/qml/Control/ListView/ThumbnailListView2.qml
- src/qml/main.qml
修复相册为空时，相册卡死的问题
Log: 修复相册为空时，相册卡死的问题
> fix: 修复相册为空时，相册卡死的问题

- src/qml/Control/ListView/ThumbnailListDelegate2.qml
- src/qml/PreviewImageViewer/ImageViewer.qml
修复无效图片未显示撕裂图的问题
Log: 修复无效图片未显示撕裂图的问题
> fix: 修复无效图片未显示撕裂图的问题

- src/qml/GlobalVar.qml
- src/qml/PreviewImageViewer/OpenImageWidget.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/filecontrol.cpp
- src/src/filecontrol.h
添加打开不支持格式图片处理逻辑，给出"该文件格式不支持"提示
Log: 添加打开不支持格式图片处理逻辑，给出"该文件格式不支持"提示
Bug: https://pms.uniontech.com/bug-view-165049.html
> feat: 添加打开不支持格式图片处理逻辑，给出"该文件格式不支持"提示

- src/qml/MainAlbumView.qml
- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/PreviewImageViewer/ToolBarThumbnailListView.qml
- src/qml/SideBar/Sidebar.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/src/albumControl.cpp
- src/src/thumbnailview/imagedatamodel.cpp
优化外设挂载流程，相册启动时不加载设备列表视图内容
Log: 优化外设挂载流程，相册启动时不加载设备列表视图内容
> chore: 优化外设挂载流程，相册启动时不加载设备列表视图内容

- debian/changelog
update version to 5.10.13
Log: update version to 5.10.13
> chore: update version to 5.10.13

- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
1.修复合集-所有项目视图左上角时间范围标签不显示的问题
2.修复合集-所有项目视图底部未与底栏对齐的问题
Log: 合集-所有项目视图UI问题修改
> fix: 合集-所有项目视图UI问题修改

- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
修复年/月视图图片内容未跟随窗口大小等比例缩放的问题
Log: 修复年/月视图图片内容未跟随窗口大小等比例缩放的问题
> fix: 修复年/月视图图片内容未跟随窗口大小等比例缩放的问题

- debian/changelog
update V6.0.2
Log: update V6.0.2
> chore: update V6.0.2

- src/album/albumview/albumview.cpp
- src/album/allpicview/allpicview.cpp
- src/album/importtimelineview/importtimelineview.cpp
- src/album/searchview/searchview.cpp
- src/album/thumbnail/thumbnaillistview.cpp
- src/album/timelineview/timelineview.cpp
添加底栏模糊透明效果
Log: 添加底栏模糊透明效果
Bug: https://pms.uniontech.com/bug-view-156957.html
> feat: 添加底栏模糊透明效果

- src/album/thumbnail/thumbnaillistview.cpp
调整缩略图列表右边距
Log: 修复缩略图左右边距不一致的问题
Bug: https://pms.uniontech.com/bug-view-156959.html
> fix: 修复缩略图左右边距不一致的问题

- debian/changelog
Update version to 5.10.14
相关PR:
* #130
* #131
* #133
* #134
* #135
Log: Update version to 5.10.14
Bug: https://pms.uniontech.com/bug-view-191409.html
Bug: https://pms.uniontech.com/bug-view-164375.html
Bug: https://pms.uniontech.com/bug-view-138675.html
Bug: https://pms.uniontech.com/bug-view-156957.html
Bug: https://pms.uniontech.com/bug-view-156959.html
> chore: Update version to 5.10.14

- src/album/dialogs/albumcreatedialog.cpp
【UI】新建相册对话框，输入字体样式调整
Log: 【UI】新建相册对话框，输入字体样式调整
Bug: https://pms.uniontech.com/bug-view-194207.html
> chore: 【UI】新建相册对话框，输入字体样式调整

- src/album/widgets/expansionpanel.cpp
【UI】筛选下拉框样式调整
Log: 【UI】筛选下拉框样式调整
Bug: https://pms.uniontech.com/bug-view-194209.html
> chore: 【UI】筛选下拉框样式调整

- src/album/mainwindow.cpp
- src/album/widgets/albumlefttabitem.cpp
- src/album/widgets/ddlabel.cpp
- src/album/widgets/flatbutton.cpp
- src/album/widgets/flatbutton.h
20230420修复UI专题
1.删除对话框居中显示
2.暗色主题，标题栏悬浮色修改
3.侧边栏导航项悬浮提示逻辑完善，仅在显示不全时才显示浮框提示
> 20230420修复UI专题

- debian/changelog
Update version to 5.10.16(community)
Log: Update version to 5.10.16(community)
> chore: Update version to 5.10.16(community)

- debian/changelog
Update version to 5.10.18(Community)
Log: Update version to 5.10.18(Community)
> chore: Update version to 5.10.18(Community)

- src/src/filecontrol.cpp
针对传入path，统一变更为绝对路径，增强接口参数兼容性，能够传入绝对路径或带file://的url路径
Log: 优化isImge、isVideo接口处理逻辑
Bug: https://pms.uniontech.com/bug-view-192995.html
> chore: 优化isImage、isVideo接口处理逻辑

- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/filecontrol.cpp
- src/src/imageengine/imageenginethread.cpp
- src/src/imageengine/movieservice.cpp
- src/src/thumbnailload.cpp
- src/src/unionimage/unionimage.cpp
- src/src/unionimage/unionimage.h
url路径转本地路径整改，统一使用localPath接口处理
Log:  url路径转本地路径整改，统一使用localPath接口处理
> chore: url路径转本地路径整改，统一使用localPath接口处理

- src/album/main.cpp
点击图片打开时，show() 重置了窗口状态，重新设置标题栏模式。
Log: Adapt comapct mode with click image.
Influence: CompactMode
> fix: Adapt comapct mode with click image.

- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/src/albumControl.cpp
- src/src/unionimage/imageutils.cpp
1.gvfs挂载路径判断逻辑优化
2.针对file前缀外设路径，添加canEject，判断是否为外设
3.设备列表加载逻辑优化
Log: "从文件导入"和设备列表功能完善
> refator: "从文件导入"和设备列表功能完善

- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/Control/ListView/ThumbnailListDelegate2.qml
[UI] Optimize thumbnail display effect
Log: [UI] Optimize thumbnail display effect
Bug: https://pms.uniontech.com/bug-view-192973.html
> chore: [UI] Optimize thumbnail display effect

- src/deepin-album.qrc
- src/qml/Control/BorderImageEx.qml
- src/qml/Control/MonthImage.qml
- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
- src/qml/ThumbnailImageView/NoPictureView.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/thumbnailload.cpp
- src/src/thumbnailload.h
1.Preview image stretched proportionally
2.And preview Image Border
3.Optimization of monthly view segmentation line display effect
Log: [UI] Adjusting the display effect of year and year views
Bug: https://pms.uniontech.com/bug-view-168163.html
> fix: [UI] Adjusting the display effect of year and year views

- src/qml/AlbumTitle.qml
- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/MainAlbumView.qml
- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
- src/qml/ThumbnailImageView/NoPictureView.qml
- src/qml/ThumbnailImageView/ThumbnailImage.qml
- src/qml/main.qml
- src/src/globalstatus.cpp
- src/src/globalstatus.h
1.Imported view eliminates thumbnail excess projection boundaries
2.NoPicture View adjust to horizontal align
3.Adjust the aspect ratio of the year/month view preview to 7:4
4.Optimization of title Bar background color display at minimum size
Log: [UI] fix some bugs
> fix: [UI] fix some bugs

- debian/changelog
Update version to 5.10.20
相关PR:
* #187
* #188
Log: Update version to 5.10.20
> chore: Update version to 5.10.20

- src/album/albumview/albumview.cpp
- src/album/albumview/leftlistview.cpp
- src/album/imageengine/imageenginethread.cpp
- src/album/utils/classifyutils.cpp
- src/album/utils/classifyutils.h
适配图像分类DBus接口
Log: 适配图像分类DBus接口
> feat: 适配图像分类DBus接口

- src/album/dbmanager/dbmanager.cpp
- src/album/thumbnail/thumbnaildelegate.cpp
Resolve the issue of no images in trash after deleting images
Log: Resolve the issue of no images in trash after deleting images
Bug: https://pms.uniontech.com/bug-view-231739.html
> fix: Resolve the issue of no images in trash after deleting images

- src/album/albumview/albumview.cpp
- src/album/albumview/albumview.h
- src/album/mainwindow.cpp
Right click on the photo classification detail page to add a slideshow function
Log: Right click on the photo classification detail page to add a slideshow function
Bug: https://pms.uniontech.com/bug-view-232599.html
> fix: Right click on the photo classification detail page to add a slideshow function

- debian/changelog
Update version to 5.10.21(Community)
相关PR:
* #191
* #192
* #201
Log: Update version to 5.10.21(Community)
> chore: Update version to 5.10.21(Community)

- src/album/controller/exporter.cpp
Improve the function of batch exporting images
Log: Improve the function of batch exporting images
Bug: https://pms.uniontech.com/bug-view-237179.html
> fix: Improve the function of batch exporting images

- debian/changelog
Update version to 5.10.22
相关PR:
* #203
Log: Update version to 5.10.22
> chore: Update version to 5.10.22

- src/album/controller/wallpapersetter.cpp
设置壁纸同时设置锁屏壁纸
Log: 设置壁纸同时设置锁屏壁纸
Bug: https://pms.uniontech.com/story-view-32367.html
Influence: SetWallpaper
> feat: Set greeter background when setting wallpaper

- debian/changelog
Bump version to 5.10.24
Bump version to 5.10.24
> chore: Bump version to 5.10.24

- src/qml/Control/ListView/ThumbnailListViewTools.js
- src/src/albumControl.cpp
Fix the issue of abnormal video viewing function
Log: Fix the issue of abnormal video viewing function
Bug: https://pms.uniontech.com/bug-view-229703.html
> fix: Fix the issue of abnormal video viewing function

- src/qml/AlbumTitle.qml
- src/translations/deepin-album.ts
- src/translations/deepin-album_zh_CN.ts
add tooltip for import button
Log: add tooltip for import button
Bug: https://pms.uniontech.com/bug-view-219021.html
> fix: add tooltip for import button

- src/qml/AlbumTitle.qml
- src/qml/MainAlbumView.qml
Sidebar animation logic adjustment
Log: Sidebar animation logic adjustment
Bug: https://pms.uniontech.com/bug-view-194909.html
> fix: Sidebar animation logic adjustment

- src/src/albumControl.cpp
- src/src/globalstatus.cpp
- src/translations/deepin-album.ts
- src/translations/deepin-album_zh_CN.ts
- src/translations/deepin-album_zh_HK.ts
- src/translations/deepin-album_zh_TW.ts
1.Adjust the minimum size to avoid overlapping space in the title bar
2.Update the new album name copy
3.Time Range Chinese Display Update
Log: fix UI bugs
Bug: https://pms.uniontech.com/bug-view-218997.html, https://pms.uniontech.com/bug-view-193021.html, https://pms.uniontech.com/bug-view-193009.html
> fix: fix UI bugs

- src/qml/Control/ListView/ThumbnailListView.qml
- src/qml/Control/ListView/ThumbnailListView2.qml
Remove the additional arrows from the menu
Log: Remove the additional arrows from the menu
Bug: https://pms.uniontech.com/bug-view-168229.html
> fix: Remove the additional arrows from the menu

- src/qml/Control/FilterComboBox.qml
- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CustomAlbum/CustomAlbum.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml
[UI] adjust combobox UI pop style
Log: [UI] adjust combobox UI popstyle
Bug: https://pms.uniontech.com/bug-view-168279.html
> fix: [UI] adjust combobox UI pop style

- src/qml/Control/DeleteDialog.qml
- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/Control/ListView/ThumbnailListDelegate2.qml
- src/qml/Control/ListView/VideoLabel.qml
Fix the issue of video duration exceeding the tag background
Log: Fix the issue of video duration exceeding the tag background
Bug: https://pms.uniontech.com/bug-view-219155.html
> fix: Fix the issue of video duration exceeding the tag background

- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/Control/ListView/ThumbnailListDelegate2.qml
Log: Handled the problem that when the height/width of the image is too small, the actual size of the display style is incorrect and the interface problem when the image is displayed in the original scale.
BUG: https://pms.uniontech.com/bug-view-219009.html
https://pms.uniontech.com/bug-view-168397.html
> fix: Problems caused by image display ratio

- src/qml/Control/Animation/SwitchViewAnimation.qml
- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/Control/ListView/ThumbnailListDelegate2.qml
- src/qml/Control/ListView/ThumbnailListView2.qml
- src/qml/GlobalVar.qml
- src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/globalstatus.cpp
- src/src/globalstatus.h
- src/src/thumbnailview/imagedatamodel.cpp
- src/src/thumbnailview/imagedatamodel.h
- src/src/thumbnailview/qimageitem.cpp
- src/src/types.h
Add Scale Switching Animation
Log: [Animation] Add Scale Switching Animation
> feat: [Animation] Add Scale Switching Animation

- src/deepin-album.qrc
- src/qml/AlbumTitle.qml
- src/qml/Control/Animation/FadeInoutAnimation.qml
- src/qml/Control/ListView/ThumbnailListView2.qml
- src/qml/Control/ListView/ThumbnailListViewTools.js
- src/qml/GlobalVar.qml
- src/qml/MainAlbumView.qml
- src/qml/PreviewImageViewer/FullThumbnail.qml
- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/PreviewImageViewer/MainStack.qml
- src/qml/PreviewImageViewer/ViewTopTitle.qml
- src/qml/StackControl.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
- src/qml/main.qml
- src/src/thumbnailview/qimageitem.cpp
Add large image preview animation
Log: [Animation] Add large image preview animation
> feat: [Animation] Add large image preview animation

- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
Log: Problems with time and title display in day view/imported sliding items
Bug: https://pms.uniontech.com/bug-view-168303.html
> fix: Optimize the title bar of the import screen and day screen

- src/qml/AlbumTitle.qml
- src/qml/Control/Animation/SwitchViewAnimation.qml
- src/qml/Control/ListView/ThumbnailListDelegate2.qml
- src/qml/MainAlbumView.qml
- src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/MonthCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/YearCollection.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
- src/qml/main.qml
- src/src/globalstatus.cpp
- src/src/globalstatus.h
Trigger ratio animation only when clicking the ratio button
Log: Trigger ratio animation only when clicking the ratio button
> fix: Trigger ratio animation only when clicking the ratio button

- src/qml/Control/Animation/FadeInoutAnimation.qml
- src/qml/Control/BaseView.qml
- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/CustomAlbum/CustomAlbum.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/qml/ThumbnailImageView/HaveImportedView/ImportedlListView.qml
- src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml
- src/qml/ThumbnailImageView/SearchView.qml
- src/qml/ThumbnailImageView/ThumbnailImage.qml
- src/src/globalstatus.cpp
- src/src/globalstatus.h
add sidebar switch animation
Log: add sidebar switch animation
> feat: [Animation] add sidebar switch animation

- debian/changelog
Add sidebar menu switching animation.
Add large image preview animation.
Add dynamic effects for switching between year, month, and day views. 
Increase the proportion of images to switch dynamic effects.
Log: Update version to 6.0.5
> chore: Update version to 6.0.5

- src/qml/AlbumTitle.qml
Search box centering issue fixed
Log: Search box centering issue fixed
Bug: https://pms.uniontech.com/bug-view-219083.html
> fix: Search box centering issue fixed

- src/qml/Control/Animation/SwitchViewAnimation.qml
- src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
- src/src/types.h
[Animation] Collection year month day view add zoom out fade out dynamic effect
Log: [Animation] Collection year month day view add zoom out fade out dynamic effect
> feat: [Animation] Collection year month day view add zoom out fade out dynamic effect

- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/PreviewImageViewer/ToolBarThumbnailListView.qml
- src/qml/StackControl.qml
- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/CollecttionView.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/qml/ThumbnailImageView/CustomAlbum/CustomAlbum.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/src/globalstatus.cpp
- src/src/globalstatus.h
Add large image preview with reverse animation effect
Log: [Animation] Add large image preview with reverse animation effect
> feat: [Animation] Add large image preview with reverse animation effect

- src/qml/Control/Animation/FadeInoutAnimation.qml
- src/qml/MainAlbumView.qml
- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/StackControl.qml
- src/src/configsetter.cpp
- src/src/globalstatus.cpp
- src/src/globalstatus.h
Add large image preview animation duration config
Log: [Config] Add large image preview animation duration config
> feat: [Config] Add large image preview animation duration config

- src/qml/Control/ListView/ThumbnailListViewTools.js
- src/qml/MainAlbumView.qml
- src/qml/StackControl.qml
- src/src/globalcontrol.cpp
- src/src/utils/rotateimagehelper.cpp
Resolve the issue of asynchronous rotation between image components and photo albums
Log: Resolve the issue of asynchronous rotation between image components and photo albums
Bug: https://pms.uniontech.com/bug-view-269765.html
> fix: Resolve the issue of asynchronous rotation between image components and photo albums

- src/src/unionimage/baseutils.h
- src/src/utils/devicehelper.cpp
- src/src/utils/filetrashhelper.cpp
- src/src/utils/filetrashhelper.h
Adapt V25 dde-file-manager dbus service name changed
Log: Adapt V25 dde-file-manager dbus service name changed
> chore: [dbus] Adapt V25 dde-file-manager dbus service name changed

- src/album/mainwindow.cpp
- src/album/mainwindow.h
fix the album permission control problem  when import photo
Log: fix the album permission control problem  when import photo
Bug: https://pms.uniontech.com/bug-view-270731.html
> fix: the album permission control problem

- debian/changelog
update version to 6.0.10
Log: update version to 6.0.10
Task: https://pms.uniontech.com/task-view-366297.html
> chore: update version to 6.0.10

- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CustomAlbum/CustomAlbum.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/qml/ThumbnailImageView/HaveImportedView/HaveImportedView.qml
- src/qml/ThumbnailImageView/RecentlyDeletedView/RecentlyDeletedView.qml
- src/qml/ThumbnailImageView/SearchView.qml
- src/src/configsetter.cpp
- src/src/globalstatus.cpp
- src/src/globalstatus.h
1. add config enable/disable sidebar switch animation
2. default to disabled
Log: add config enable/disable sidebar switch animation
Task: https://pms.uniontech.com/story-view-36403.html
> chore: [animation] add config enable/disable sidebar switch animation

- debian/changelog
update version to 6.0.11
Log: update version to 6.0.11
> chore: update version to 6.0.11

- README.md
- README.zh_CN.md
- debian/control
- src/CMakeLists.txt
- src/src/imagedata/imageprovider.cpp
- src/src/unionimage/imageutils.cpp
- src/src/unionimage/unionimage.cpp
Remove the freeimage dependency
Log: Remove the freeimage dependency
> fix: Remove the freeimage dependency

- src/qml/SideBar/SideBarItem.qml
DTK api update, adjust sidebar background color.
Log: Adjust sidebar background color.
Bug: https://pms.uniontech.com/bug-view-290603.html
Influence: UI
> fix: sidebar background color

- debian/changelog
- linglong.yaml
Bump version to 6.0.12
Log: Bump version to 6.0.12
> chore: Bump version to 6.0.12

- README.md
- README.zh_CN.md
remove invalid  url
Log: remove invalid  url
> fix: remove invalid  url

- debian/changelog
- linglong.yaml
Bump version to 6.0.15
Log: Bump version to 6.0.15
> chore: Bump version to 6.0.15

- .gitignore
- arm64/linglong.yaml
- debian/control
- debian/rules
- deploy_dep
- install_dep
- linglong.yaml
- loong64/linglong.yaml
- src/CMakeLists.txt
- src/main.cpp
- src/src/imageengine/movieservice.cpp
Enable linglong build and fix some runtime issues.
Log: Enable linglong build.
> chore: Enable linglong build

- src/qml/AlbumTitle.qml
- src/qml/main.qml
Force exit when quit from menu.
Log: Fix segment error if menu quit.
> fix: Fix segment error if menu quit

- src/qml/AlbumTitle.qml
- src/qml/Control/NewAlbumDialog.qml
- src/qml/MainAlbumView.qml
- src/qml/PreviewImageViewer/ImageViewer.qml
- src/qml/PreviewImageViewer/InformationDialog/InformationDialog.qml
- src/qml/PreviewImageViewer/ViewRightMenu.qml
- src/qml/SideBar/SideBarItemDelegate.qml
- src/qml/SideBar/Sidebar.qml
- src/qml/StackControl.qml
Fix some issues which refer to bug list.
Log: Fix some issues.
Bug:
https://pms.uniontech.com/bug-view-296281.html
https://pms.uniontech.com/bug-view-289575.html
https://pms.uniontech.com/bug-view-289237.html
https://pms.uniontech.com/bug-view-289235.html
https://pms.uniontech.com/bug-view-289233.html
https://pms.uniontech.com/bug-view-276743.html
> fix: Fix some issues

- .gitignore
- src/src/albumControl.cpp
Use the DBus call replace process call.
Log: Fix can not play video issue.
Bug: https://pms.uniontech.com/bug-view-303907.html
> fix: Fix can not play video issue

- src/qml/Control/ListView/ThumbnailListDelegate.qml
- src/qml/Control/ListView/ThumbnailListViewAlbum.qml
- src/qml/ThumbnailImageView/DeviceAlbum/DeviceAlbum.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/thumbnailview/imagedatamodel.cpp
- src/src/thumbnailview/imagedatamodel.h
[fix: component overlap on deleted view](https://github.com/linuxdeepin/deepin-album/commit/51bc2c57f5b260de6db93101f3592bf0f4505411) 
As title.
Log: fix a ui issue.
Bug: https://pms.uniontech.com/bug-view-275475.html
[fix: app hangs when access mtp device](https://github.com/linuxdeepin/deepin-album/commit/333f636b139c74bd51dc2a5ab304991ac07b915d) 
As title.
Log: fix a access issue.
Bug: https://pms.uniontech.com/bug-view-289223.html
> fix: component overlap / app hangs

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Bump version to 6.0.17
Log: Bump version to 6.0.17
> chore: Bump version to 6.0.17

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Bump version to 6.0.18
Log: Bump version to 6.0.18
> chore: Bump version to 6.0.18

- .gitignore
- src/qml/MainAlbumView.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/imageengine/imageenginethread.cpp
- src/src/imageengine/imageenginethread.h
It should not import this file if it is a bad format image or video.
Log: Fix enable to import bad format image or video issue.
Bug: https://pms.uniontech.com/bug-view-289229.html
> fix: Fix enable to import bad format image or video issue

- src/qml/MainAlbumView.qml
- src/qml/MenuItemStates.qml
- src/qml/ThumbnailImageView/CollecttionView/AllCollection.qml
- src/qml/ThumbnailImageView/CollecttionView/DayCollection.qml
- src/src/albumControl.cpp
- src/src/albumControl.h
- src/src/dbmanager/dbmanager.cpp
Delay to close dialog in order to show for user. Do not update model if the view is not visiable, that cause block if there are images.
Log: Fix progress dialog not show issue.
Bug: https://pms.uniontech.com/bug-view-289195.html
> fix: Fix progress dialog not show issue

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
New version 6.0.19
Log: New version 6.0.19
> chore: New version 6.0.19

- src/qml/Control/DeleteDialog.qml
- src/qml/Control/ExportDialog.qml
- src/qml/Control/NewAlbumDialog.qml
- src/qml/Control/RemoveAlbumDialog.qml
- src/qml/PopProgress/StandardProgressDialog.qml
- src/qml/PreviewImageViewer/Dialog/RemoveDialog.qml
- src/qml/PreviewImageViewer/ReName.qml
After change the theme, the text color is not changed to highlight.
Log: Fix dialog text color issue after change theme. 
Bug: https://pms.uniontech.com/bug-view-307703.html
https://pms.uniontech.com/bug-view-300269.html
> fix: Fix text color issue after change theme

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
New tag v6.0.20 release.
Log: New tag v6.0.20.
> chore: [tag] New tag v6.0.20
